apiVersion: apps/v1
kind: Deployment
metadata:
  name: distilgpt2
  namespace: demo
  labels:
    app: distilgpt2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distilgpt2
  template:
    metadata:
      labels:
        app: distilgpt2
    spec:
      containers:
      - image: maheshkumar5859/sentiment-analysis1:latest
        name: distilgpt2
        ports:
        - containerPort: 8000
