apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demo
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: gcr.io/rig-cto-coe-cloud-coe-gcp/distilgpt2@sha256:3e6db989c8190d0baa9883acb3560dfc55d31008f6ef53690136c3d052fda085
        name: distilgpt2
        ports:
        - containerPort: 80
