apiVersion: apps/v1
kind: Deployment
metadata:
  name: distilgpt2
  namespace: demo
  labels:
    app: distilgpt2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distilgpt2
  template:
    metadata:
      labels:
        app: distilgpt2
    spec:
      containers:
      - image: nginx:stable-alpine3.19-perl
        name: nginx
        ports:
        - containerPort: 3003
