apiVersion: apps/v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: demo-ml
  name: demo-svc
  namespace: demo-ml
spec:
  ports:
    - nodePort: 31168
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx
  type: NodePort
