apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: distilgpt2
spec:
  type: LoadBalancer
  selector:
    app: distilgpt2
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
