apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: demo-ml
  name: demo-svc
  namespace: demo
spec:
  ports:
    - nodePort: 31268
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: distilgpt2
  type: NodePort
