apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  namespace: demo
spec:
  ports:
    - nodePort: 31168
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: distilgpt2
  type: NodePort
